[package]
name = "vint"
version = "0.1.0"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]

[dependencies]
bitfield = "0.12.1"
serde = "1.0"
serde_derive = "1.0"
serde_bytes = "0.10.4"
bincode = "1.0.0"
mayda = {path = "../mayda"}
rand = "0.4"
snap = "0.2"
fnv = "1.0.3"
byteorder = "1.2.2"
criterion = "0.2.2"
quickcheck = "0.6"
quickcheck_macros = "0.6"

[[bench]]
name = "bench"
harness = false