[package]
name = "vint"
version = "0.1.0"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]

[dependencies]
bitfield = "0.12.1"
rand = "0.4"
snap = "0.2"
byteorder = "1.2.2"
criterion = "0.2.2"
quickcheck = "0.6"
quickcheck_macros = "0.6"

[[bench]]
name = "bench"
harness = false